DNA_string = "GGCGAACTACGGCGCGCGCGTTTTCTATAGACAGAAATATTGGTCGAGCTCGACGAACCCATTGTACCTGCCAGTAGAAATATGGACGTGCCGCGTCGGGCGTAGAACGTATGATTACAAAGGCCAGACATCTCATCCTGATCTCGCCAGTATGCGTCATAGGCTCGCATGCTTCGCATGATCAAAGCATGCCTCTCTGGAGGTGGCACGAGGATGGTGACACGCAGGCCACGGATCCAGACTTTCGTACGAAGAATTATTTTTCCTACAAAGTATGACTTCTTGTTAGTAAAAAACCTCCGCGATCCGTCCCTTTGCTTCGCCCCTACTTACACAGATAGTTCCTTCCTAGGGGAGTTGCTTGTGCTAAAGCCAGAATCTCGCGTAAATATGGATTATCCCGTGGTAAGTCGAAGCACGACACGAAAACGGGGTGGCGCGTCTACTCCATTAGCTGATCGACCACATGTCATGCCGCTGGGGAGTTACGGTGCCATCGTAAATTCTAGTCAGTTGAACTCGCGTTGACTGTTTCATGGTATAGCAGCGGAACACATGTGTCATGGGACCTGATCCATGATGCCAGTAGAATCAAGAGTATTAGCTTACTACTGGGCGCCCTTAGTCTAGTGTCCTCAGCTTTTCCGCGATCACGTCTGATGAAACGCAGGCGCCCGTCATAAGGAGATTTGAACCAAAATGACCAATGCGCTTTAGGAGTTATCCACGTAGAAACCCCCCTGCAACTAGTAGGTAACAGGTCAAGTGTCGGCGCTTTATCCTGAAATTCCCGTTATGTATAATTAGTTGATATGGTGTAGGTTCGTGGGCAATTCAGCGCGTACTGTCTACTTAGGCTTGTACATCTAAGGGCAGTATTCATGTAGCAGAGGCTACGTTAAATTTGTTGAATTT"

count_A = 0
count_C = 0
count_G = 0
count_T = 0

for basa in DNA_string:
   if basa == "A":
      count_A = count_A + 1
   elif basa == "C":
      count_C = count_C + 1
   elif basa == "G":
      count_G = count_G + 1
   elif basa == "T":
      count_T = count_T+ 1

print(count_A, count_C, count_G, count_T)

#basa tuh variabel sementara di loop jadi ga perlu didefinisiin sebelum buat loop. Intinya itu buat nampung value tiap item dalam sebuah urutan saat proses looping
#string kl urutan string value dihitungnya perhuruf, kl mau perkata pake list tandanya [], kl mau ubah string ke list pake variabel.split()